name: GitHub Pulse Heart

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pulse SVG
        run: |
          mkdir -p dist
          curl https://raw.githubusercontent.com/yassinebridi/github-contributions-graph-heart/main/github-pulse.svg > dist/github-pulse.svg

      - name: Deploy to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update GitHub Pulse Heart [skip ci]"
